/**
  ******************************************************************************
  * @file    retarget.c
  * @author  Yiran Zhang
  * @github  https://github.com/yz1295
  * @brief   Retargets printf/scanf to USART2 (HAL_UART)
  *
  * This file overrides the low-level _write() used by newlib/printf
  * so you can use printf() over UART without enabling semihosting.
  *
  * Add this file to your project and make sure USART2 is initialized
  * in CubeMX (MX_USART2_UART_Init).
  ******************************************************************************
  */

#include "usart.h"
#include <stdio.h>

extern UART_HandleTypeDef huart2;  // generated by CubeMX

/**
  * @brief  Retargets the C library printf function to the USART.
  * @param  file Unused
  * @param  ptr  Pointer to string
  * @param  len  String length
  * @retval Number of characters written
  */
int _write(int file, char *ptr, int len) {
    HAL_UART_Transmit(&huart2, (uint8_t*)ptr, len, HAL_MAX_DELAY);
    return len;
}
